### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by nicolasrosa** [fregu856/evaluating_bdl#3]
Hello @fregu856,

I'm trying to run the `evaluating_bdl/depthCompletion/mcdropout_train.py` from your docker image and, as you can see, the code detects the training and validation images, but it's throwing the following error in line 75. Do you know what could be?

```
root@03559b6308a7:~# python evaluating_bdl/depthCompletion/mcdropout_train.py
DatasetKITTIAugmentation - num unique examples: 85898
DatasetKITTIAugmentation - num examples: 171796
DatasetKITTIVal - num examples: 1000
MaskedL2Gauss
model_mcdropout.py
Traceback (most recent call last):
  File "evaluating_bdl/depthCompletion/mcdropout_train.py", line 75, in <module>
    for i_iter, batch in enumerate(train_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/root/evaluating_bdl/depthCompletion/datasets.py", line 97, in __getitem__
    sparse = sparse[(img_h - new_img_h):img_h, int(img_w/2.0 - new_img_w/2.0):int(img_w/2.0 + new_img_w/2.0)] # (shape: (352, 1216))
TypeError: 'NoneType' object is not subscriptable
```

**Comment by nicolasrosa** [comment]
Sorry, I forgot to unzip the `data_depth_velodyne.zip` file.
